# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4f6d662ae7ae00e6445bc1b232b68277f0f74fff9e79affcff4d7c94065fea2e7791d3dd56e42ace98651a44094c9a3ceab0ee1e03ce7e804027efc460214b27

test:
  secret_key_base: 41e20414216a5d3f7199abe7b7368d5147cc464116257f3ee23284f98155edd0e74cd49627dc9e0e5d6c4d25090375beed9385d4ac62a6f9308984fe180e669e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
